# Generated by Django 3.2 on 2023-02-13 15:53

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Неверно введено имя', regex='^[\\w.@+-]+\\Z'), users.models.validate_username_me], verbose_name='username'),
        ),
    ]
